---
- name: MacOS Local Provisioner
  hosts: localhost
  become: no
  gather_facts: yes
  roles:
    - brew
    - zsh
    - role: git
      vars:
        git_username: Yuichiro Naruta
        git_email: y.naruta@gmail.com
    - go
    - infra
    - k8s
    - xenv
    - vscode
    - macos
