#
# set zshrc
#
- name: create zshrc
  file:
    path: ~/.zshrc
    state: touch
    mode: 0600

- name: add alias
  lineinfile:
    dest: ~/.zshrc
    line: "{{ item }}"
    state: present
  with_items:
    - "# alias"
    - 'alias ls="ls -G"'
    - 'alias ll="ls -lG"'
    - 'alias la="ls -laG"'
