#
# homebrew
#
- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: add homebrew tap repos
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - caskroom/cask
    - caskroom/versions

- name: install homebrew packages
  homebrew:
    name:
      - mas
      - vim
      - wget
      - coreutils
      - gzip
      - gawk
      - jq
      - tree
      - git
      - git-lfs
      - htop
    state: present

- name: install homebrew packages with default name
  homebrew:
    name:
      - findutils
      - grep
      - gnu-sed
      - gnu-tar
    state: present
    install_options: with-default-names

#
# homebrew cask
#
- name: install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - appcleaner
    - google-chrome
    - google-japanese-ime
    - wireshark
    - virtualbox
    - vagrant
    - xquartz
    - bettertouchtool
    - mattermost
    - skitch
    - typora
#
# mas
#
#- name: mas get installed list
#  shell: mas list
#  register: mas_installed_list
#  changed_when: False
#  check_mode: no
#
#- name: mas install items
#  shell: "mas install {{ item }}"
#  with_items:
#    - 803453959 #Slack
#  when: (item|string) not in mas_installed_list.stdout
#
