#
# install pyenv and nodenv
#
- name: install env packages
  homebrew:
    name:
      - pyenv
      - nodenv
    state: present

- name: create zshrc
  file:
    path: ~/.zshrc
    state: touch
    mode: 0600

- name: add init command to zshrc
  lineinfile:
    dest: ~/.zshrc
    line: "{{ item }}"
    state: present
  with_items:
    - "#pyenv"
    - 'eval "$(pyenv init -)"'
    - "#nodeenv"
    - 'eval "$(nodenv init -)"'
