- name: install git packages
  homebrew:
    name: git
    state: present

- name: deploy gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: deploy gitglobal ignore
  template:
    src: gitignore_global.j2
    dest: ~/.gitignore_global